### ISSUE TITLE
npm install echarts 不能安装.

### ISSUE THREAD

**Issue by HelloYie** [uooo/echarts#2]
如题:
`npm install echarts@2.2.7-webpack `  是可以安装的.
npmjs 官网的 `npm install echarts` 命令会提示zrender 依赖错误,而导致不能安装.
[https://www.npmjs.com/package/echarts](https://www.npmjs.com/package/echarts) 的 readme貌似没有更新哇?

**Comment by HelloYie** [comment]
而且安装了貌似也不能用?

**Comment by uooo** [comment]
由于 `2.2.7` 版本号已被占用，为了不与 echarts 官方版本号冲突，所以使用 `echarts@2.2.7-webpack` 版本号并内置了 `zrender@2.1.1`，因此只能使用 `npm install echarts@2.2.7-webpack` 安装echarts。
npm 中的 echarts 的 代码是最新的，只有 readme 未同步，请不用担心。

**Comment by HelloYie** [comment]
It works. 楼主实现思路是啥呢，webpack 原生支持AMD吧？

**Comment by uooo** [comment]
echarts 是AMD的，webpack 能加载 AMD 规范的 package，发布到 npm 主要是为了集成到 webpack。
