### ISSUE TITLE
Hi, 能加入ecahrts-x支持吗?

### ISSUE THREAD

**Issue by HelloYie** [uooo/echarts#6]
如题: 如果能加入echarts-x 支持的话, 是极好的.

**Comment by uooo** [comment]
我以为 echarts-x 没多少人用，所以就没处理依赖问题，等我处理好了通知你

**Comment by HelloYie** [comment]
@uooo 恩恩,谢谢楼主, 坐等 :)

**Comment by uooo** [comment]
已创建repo：https://github.com/uooo/echarts-x，可以在这进行讨论：https://github.com/uooo/echarts-x/issues/1

**Comment by uooo** [comment]
@HelloYie echarts-x 已经支持了
