### ISSUE TITLE
关于这个repo的疑惑

### ISSUE THREAD

**Issue by haoxins** [uooo/echarts#7]
你好，我从npm到达此repo

[react-echarts](https://www.npmjs.com/package/react-echarts)
[echarts-react](https://www.npmjs.com/package/echarts-react)

均指向此 repo, 但是貌似并没有封装成react component.

* 而且实在不明白为什么一个repo，发布2个npm module。有点占用资源。
* 能否释放某一个npm name，谢谢！

:smile:

**Comment by uooo** [comment]
我还在酝酿之中，如果你已经有react，当然木有问题
